stages:
  - build
  - test
  - package
  - acceptance

build:
  stage: build
  image: node:14-alpine
  script:
    - npm ci --only=production
  artifacts:
    paths:
      - node_modules/
      - server.js

unit tests:
  stage: test
  image: node:14-alpine
  before_script:
    - npm install
  script:
    - npm test

build docker image:
  stage: package
  image: docker
  services: 
    - docker:dind
  script: 
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

postman api testing:
  stage: acceptance
  image: 
    name: postman/newman
    entrypoint: [""]
  services: 
    - name: $CI_REGISTRY_IMAGE
      alias: banking-api
  script:
    - newman run test/collection.json --env-var "baseUrl=banking-api:3000"

curl api testing:
  stage: acceptance
  image: curlimages/curl
  services: 
    - name: $CI_REGISTRY_IMAGE
      alias: banking-api
  script: 
    - curl http://banking-api:3000/status | grep "UP"