stages:
  - build
  - test
  - package
  - acceptance

build:
  stage: build
  image: node:14-alpine
  script:
    - npm ci --only=production
  artifacts:
    paths:
      - node_modules/
      - src/server.js

unit tests:
  stage: test
  image: node:14-alpine
  before_script:
    - npm install
  script:
    - npm test

build docker image:
  stage: package
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services: 
    - docker:dind
  script: 
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} ${CI_REGISTRY} --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest

curl api testing:
  stage: acceptance
  image: docker
  services: 
    - docker:dind
  script: 
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} ${CI_REGISTRY} --password-stdin  
    - docker run -d -p 3000:3000 ${CI_REGISTRY_IMAGE}:latest
    - apk add curl
    - curl -I http://docker:3000/status | grep "200"